modified to use a configuration file for file locations

diff --git a/root/lamps/lamps-test b/root/lamps/lamps-test
--- a/root/lamps/lamps-test
+++ b/root/lamps/lamps-test
@@ -1,9 +1,10 @@
+#!/bin/sh
+
 # =========================================================================
 # =========================================================================
 #
-#	Dockerfile
-#	  Dockerfile to create docker image used to 
-#            install the LAMPS scripts.
+#	lamps-run
+#	  Create & Run the LAMPS containers the first time.
 #
 # =========================================================================
 #
@@ -12,7 +13,7 @@
 # @copyright © 2017. EarthWalk Software.
 # @license Licensed under the Academic Free License version 3.0
 # @package LAMPS
-# @subpackage Dockerfile
+# @subpackage lamps-run
 #
 # =========================================================================
 #
@@ -26,28 +27,24 @@
 #
 # =========================================================================
 # =========================================================================
-FROM nimmis/alpine-micro:latest
+if [ ! -n "$LCONFIG" ]
+then
+    if [ ! -f "/var/local/lamps/.lamps" ]
+    then
+        RUNFROM=$( cd $(dirname $0) ; pwd -P )
+        if [ ! -f "$RUNFROM"/.lamps" ] then
+        then
+            echo "Unable to find configuration file"
+            exit 99
+        fi
+        LCONFIG=$RUNFROM/.lamps
+    else
+      LCONFIG="/var/local/lamps/.lamps"
+    fi
+fi
 
-MAINTAINER Jay Wheeler <earthwalksoftware@gmail.com>
+echo "$LCONFIG"
+. $LCONFIG
+echo "$LAMPS_USER_NAME"
 
-#VOLUME /scripts
-#VOLUME /config
-#VOLUME /data-lamps
 
-ENV LUID=0
-ENV LGID=0
-
-ENV LAMPS=/scripts/bin
-ENV LCONFIG=/config
-ENV LDATA=/data-lamps
-
-VOLUME /scripts
-VOLUME /config
-VOLUME /data-lamps
-
-COPY root/. /
-
-COPY installLamps.sh /
-RUN chmod +x /installLamps.sh
-
-CMD ["/installLamps.sh"]
